/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-10-01 20:03:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class classInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Learners Academy</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function required() \r\n");
      out.write("{\r\n");
      out.write("\tvar cls=document.getReport.className.value;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  if (cls == 0)\r\n");
      out.write("   { \r\n");
      out.write("      alert(\"Please Select Class\");  \r\n");
      out.write("      \r\n");
      out.write("      return false; \r\n");
      out.write("   } \r\n");
      out.write("  else\r\n");
      out.write("\t  return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

response.setHeader("Cache-Control","no-cache,no-store,must-revalidate");
HttpSession session1=request.getSession();


    if(session.getAttribute("uname")==null)
    {

    	 response.sendRedirect("Login.jsp");
    }

      out.write("\r\n");
      out.write("  <br/>  \r\n");
      out.write("\r\n");
      out.write("<div align=\"right\">\r\n");
      out.write(" <form id=\"logout\" class=\"form\" action=\"logout\" method=\"post\"> <input type=\"submit\" name=\"submit\" class=\"btn btn-info btn-md\" align=\"right\" value=\"logout\" margin=\"10px\"/>\r\n");
      out.write("    </form></div>\r\n");
      out.write("\r\n");
      out.write(" <div align=\"center\">\r\n");
      out.write(" <img src=\"D:\\Phase2Project\\LearnersAcademyPro\\logo.jpg\" style=\"width:280px;height:300px;align=\"middle\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("    <div id=\"login\">\r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("         \r\n");
      out.write("            <div id=\"login-row\" class=\"row justify-content-center align-items-center\">\r\n");
      out.write("                <div id=\"login-column\" class=\"col-md-6\">\r\n");
      out.write("                    <div id=\"login-box\" class=\"col-md-12\">\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                     <form id=\"getReport\" class=\"form\" action=\"getReport\" method=\"post\" name=\"getReport\" onSubmit=\"return required();\">\r\n");
      out.write("                           \r\n");
      out.write("                            <div class=\"form-group\" align=\"left\">\r\n");
      out.write("                                  <label for=\"username\" class=\"text-info\" >Select Class:</label><br>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                  <select name=\"className\" id=\"className\" class=\"form-control\">\r\n");
      out.write("                                  <option value=\"0\">Select Class</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"1\">Class1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"2\">Class2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"3\">Class3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"4\">Class4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"5\">Class5</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"6\">Class6</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"7\">Class7</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"8\">Class8</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"9\">Class9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"10\">Class10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("     <div class=\"form-group\" align=\"left\">\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"submit\" name=\"Submit\" class=\"btn btn-info btn-md\" value=\"Submit\">\r\n");
      out.write("                            </div>     \r\n");
      out.write("                         \r\n");
      out.write("                            \r\n");
      out.write("                        </form>\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("              \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
