/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-10-01 20:04:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.report.dao.*;

public final class classReport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.report.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Learners Academy</title>\r\n");
      out.write("\r\n");
      out.write("     <style>\r\n");
      out.write("#students {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#subjects {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("   padding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#students td, #students th,#subjects td,#subjects th {\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#students tr:nth-child(even){background-color: #f2f2f2;}\r\n");
      out.write("\r\n");
      out.write("#students tr:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("#subjects tr:nth-child(even){background-color: #f2f2f2;}\r\n");
      out.write("\r\n");
      out.write("#subjects tr:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("#students th,#subjects th {\r\n");
      out.write("  padding-top: 12px;\r\n");
      out.write("  padding-bottom: 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background-color: red;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("  margin-left:-5px;\r\n");
      out.write("  margin-right:-5px;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(".column {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Clearfix (clear floats) */\r\n");
      out.write(".row::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  clear: both;\r\n");
      out.write("  display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function goBack() {\r\n");
      out.write("\t  window.history.back();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

response.setHeader("Cache-Control","no-cache,no-store,must-revalidate");
HttpSession session1=request.getSession();


    if(session.getAttribute("uname")==null)
    {

    	 response.sendRedirect("Login.jsp");
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div align=\"center\">\r\n");
      out.write(" <img src=\"D:\\Phase2Project\\LearnersAcademyPro\\logo.jpg\" style=\"width:280px;height:300px;align=\"middle\"></div>\r\n");
      out.write("\r\n");
      out.write(" <h3 style=\"color:red;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Class");
      out.print(request.getParameter("cls") );
      out.write(" Report :</h3>\r\n");
      out.write("                           \r\n");
      out.write("        <div class=\"container\" width=\"80%\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                     <form id=\"clsReport\" class=\"form\" action=\"\"  name=\"clsReport\" >\r\n");
      out.write("                            <h3 class=\"text-info\"></h3>\r\n");
      out.write("                          \r\n");
      out.write("                       \r\n");
      out.write("  ");

	String classId=request.getParameter("cls");
	 
	ReportDao ob=new ReportDao();
	ResultSet rs=ob.getStudents(Integer.parseInt(classId));
	ResultSet rs1=ob.getSubjects(Integer.parseInt(classId));
	
	String stuData="";
	try {
	
			      
		out.write( "<div class='row'>");
	      
	    out.write( "<div class='column'>");
	    
		out.write("<table id='students'>" +
			       "<tr style='background-color:#c8dce0'>" +
			       "<td >SNo</td>" +
			       
			       "<td>Student Name</td>" +
			      
			       
			       "</tr>");
		
		while(rs.next())
		{
		
			out.write("<tr>");
				    out.write("<td>");
				    out.write(rs.getString(1));
				    out.write("</td><td>");
				    out.write(rs.getString(2)+" "+rs.getString(3));
				    out.write("</td>");
					out.write("</tr>");
		}
		
		
		
	
		
			
		
		 out.write("</table>"); 
		 out.write("</div>"); 
	
		 out.write( "<div class='column'>");
		 
		 out.write("<table id='subjects'>" +
			       "<tr style='background-color:#c8dce0'>" +
			       "<td >SNo</td>" +
			       "<td >Subjects</td>" +
			       
			       "<td>Teacher</td>" +
			      
			       
			       "</tr>");
		
		while(rs1.next())
		{
		
			out.write("<tr>");
				    out.write("<td>");
				    out.write(rs1.getString(1));
				    out.write("</td><td>");
				    out.write(rs1.getString(2));
				    out.write("</td><td>");
				    out.write(rs1.getString(3)+" "+rs1.getString(4));
				    out.write("</td>");
					out.write("</tr>");
		}
		
		
		
	
		
			
		
		 out.write("</table>"); 
		 out.write("</div>");
		 out.write("</div>");
       
		out.write("</div>"); 
		
		 
	} catch (SQLException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}


      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                            \r\n");
      out.write("                        </form>\r\n");
      out.write("                       \r\n");
      out.write("   \r\n");
      out.write("        </div>\r\n");
      out.write("    <br/>\r\n");
      out.write("      <form id=\"logout\" class=\"form\" action=\"logout\" method=\"post\">\r\n");
      out.write("                                \r\n");
      out.write(" <div align=\"center\"><a href=\"classInfo.jsp\" class=\"btn btn-info btn-md\">Back</a> <input type=\"submit\" name=\"submit\" class=\"btn btn-info btn-md\" value=\"logout\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    </div></form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
